# Generated by Django 4.1.5 on 2023-01-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0002_alter_cart_customer_delete_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartproducts",
                to="ecomapp.cart",
            ),
        ),
    ]
