# Generated by Django 4.1.5 on 2023-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0008_historicalorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="about_to_end",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="about_to_end",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
