# Generated by Django 4.1.5 on 2023-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0009_historicalproduct_about_to_end_product_about_to_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="min_quantity_to_end",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="min_quantity_to_end",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="about_to_end",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="about_to_end",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
