# Generated by Django 4.1.5 on 2023-01-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0011_alter_cartproduct_cart_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecomapp.cart"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="ecomapp.category"
            ),
        ),
    ]
